### ISSUE TITLE
Missing whitespace characters

### ISSUE THREAD

**Issue by flopma** [hackorama/java-props-in-python#1]
Hello,

Thx for this piece of code.

When reviewing it agains the Properties file from JDK 7, I found out that at line 32, the regex is missing the following chars '\t' and '\f'. So to sum up, the following five chars can be treated as separators between keys and values

' '
':'
'='
'\t'
'\f'

https://github.com/hackorama/java-props-in-python/blob/master/jprops.py#L32

Thx

**Comment by hackorama** [comment]
Thank you @flopma , this is now fixed in https://github.com/hackorama/java-props-in-python/commit/271f99736e2fce683d9399e6d326a4c35dfdb94a
